### ISSUE TITLE
imwrite permission denied

### ISSUE THREAD

**Issue by Thevaporiser** [KillingJoke42/QuantNet#1]
While running the code to create dataset, the imwrite function gives an error:-
.
.
Unable to open file "/Users/priyanshringe/Documents/QuantNet/mnistquant2bit/1.bmp" for writing.  You might not have write permission.

**Comment by KillingJoke42** [comment]
Try adding double slashes "//" in the path. 
Also verify if the path exists, which is most possibly true but might be a good idea to verify again
